### ISSUE TITLE
Text detection is failed (EasyOCREngine)

### ISSUE THREAD

**Issue by MikkiMinni** [Danily07/Translumo#96]
Здравствуйте, получаю ошибку Text detection is failed (EasyOCREngine), вот лог - [log20240203.txt](https://github.com/Danily07/Translumo/files/14151866/log20240203.txt)
Системные характеристики
ОС: Win10 22H2
Процессор: I7-10700K
Память: 16 GB
Видеокарта: kfa2 4070

**Comment by fabnicolas** [comment]
Hi!

I actually found a fix for this and I wanna report it to the developers that I found a solution.

As I searched through logs, I noticed:
`Python.Runtime.PythonException: module 'PIL.Image' has no attribute 'ANTIALIAS'`

As I discovered from a bit of searching, this happened because an internal module used by EasyOCR (Pillow) got updated to version 10.0.0.

I applied the solution to this project at the following line:
`.......\Translumo\Python\Lib\site-packages\easyocr\utils.py`

by replacing line 532, 533 and 534 like this:
`        img = cv2.resize(img,(model_height,int(model_height*ratio)), interpolation=Image.LANCZOS)
    else:
        img = cv2.resize(img,(int(model_height*ratio),model_height),interpolation=Image.LANCZOS)`

so, changing the word ANTIALIAS with LANCZOS.
Under the hood, it's the same algorithm; it only got renamed.

After restarting Translumo, EasyOCR works in latest version (v0.9.5).




I hope it helps someone!

**Comment by MikkiMinni** [comment]
> Hi!
> 
> I actually found a fix for this and I wanna report it to the developers that I have found a solution.
> 
> As I searched through logs, I noticed: `Python.Runtime.PythonException: module 'PIL.Image' has no attribute 'ANTIALIAS'`
> 
> As I discovered from a bit of searching, this happened because an internal module used by EasyOCR (Pillow) got updated to version 10.0.0.
> 
> I applied the solution to this project at the following line: `.......\Translumo\Python\Lib\site-packages\easyocr\utils.py`
> 
> by replacing line 532, 533 and 534 like this:
> 
> ```
>      img = cv2.resize(img,(model_height,int(model_height*ratio)), interpolation=Image.LANCZOS)
>     else:
>      img = cv2.resize(img,(int(model_height*ratio),model_height),interpolation=Image.LANCZOS)
> ```
> 
> so, changing the word ANTIALIAS with LANCZOS. Under the hood, it's the same algorithm; it only got renamed.
> 
> After restarting Translumo, EasyOCR works in latest version (v0.9.5).
> 
> I hope it helps someone!

Excellent, thank you very much, this solved the problem!
